name: CI

on:
  push:
  workflow_dispatch:

jobs:
  lint_and_test:
    name: Lint and Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4 # ソースコードをチェックアウト

      - name: Setup
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x
          cache: true

      - name: Run Linter
        run: deno lint

      - name: Run Tests
        run: deno test
